version: '3'

services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: node-app
    networks:
      - node-network
    ports:
      - "3000:3000"
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s docker-entrypoint.sh
    command: npm start
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    tty: true
    networks:
      - node-network
    volumes:
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root

networks:
  node-network:
    driver: bridge