version: '3'

services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: luizgustavoob/fc-challenge-docker-node:latest
    container_name: node-app
    hostname: app
    networks:
      - node-network
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s docker-entrypoint.sh
    command: npm start
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    tty: true
    networks:
      - node-network
    volumes:
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: luizgustavoob/fc-challenge-docker-nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - node-network
    depends_on:
      - app

networks:
  node-network:
    driver: bridge